// Simulation main for the regression benches.
//
// Same loop as the main generated by `verilator --binary`, plus two
// additions: a run that ends without $finish fails, and when the model is
// built with --coverage-user, coverage is written to the file named by
// +COVERAGE_FILE=<path> (Verilator 5.020 has no runtime option for this).
//
// Build with -CFLAGS -DTB_TOP_CLASS=V<top>, the generated model class.

#include "verilated.h"
#if VM_COVERAGE
#include "verilated_cov.h"
#endif
#define TB_STRINGIFY_(x) #x
#define TB_STRINGIFY(x) TB_STRINGIFY_(x)
#include TB_STRINGIFY(TB_TOP_CLASS.h)

#include <memory>
#include <string>

int main(int argc, char** argv) {
    const std::unique_ptr<VerilatedContext> contextp{new VerilatedContext};
    contextp->commandArgs(argc, argv);

    const std::unique_ptr<TB_TOP_CLASS> topp{new TB_TOP_CLASS{contextp.get()}};

    while (!contextp->gotFinish()) {
        topp->eval();
        if (!topp->eventsPending()) break;
        contextp->time(topp->nextTimeSlot());
    }

    const bool finished = contextp->gotFinish();
    topp->final();

#if VM_COVERAGE
    const std::string match = contextp->commandArgsPlusMatch("COVERAGE_FILE=");
    if (!match.empty()) {
        const std::string path = match.substr(std::string("+COVERAGE_FILE=").size());
        contextp->coveragep()->write(path.c_str());
    }
#endif

    if (!finished) {
        VL_PRINTF("%%Error: simulation ended without $finish\n");
        return 1;
    }
    return 0;
}
